import test from 'node:test';
import assert from 'node:assert/strict';
import { SpaceAudio, SOUND_CUES, audioPreferences, AUDIO_DEFAULTS } from '../src/audio.js';
class Param { constructor(){this.value=0;}setValueAtTime(v){assert.ok(Number.isFinite(v));}linearRampToValueAtTime(v){assert.ok(Number.isFinite(v));}exponentialRampToValueAtTime(v){assert.ok(v>0);}setTargetAtTime(v){this.value=v;assert.ok(Number.isFinite(v));} }
class Node {constructor(){this.gain=new Param();this.frequency=new Param();this.detune=new Param();this.pan=new Param();this.threshold=new Param();this.knee=new Param();this.ratio=new Param();this.attack=new Param();this.release=new Param();this.started=[];this.stopped=[];}connect(){}disconnect(){}start(t){this.started.push(t);}stop(t){this.stopped.push(t);}}
class Context {constructor(){this.state='suspended';this.currentTime=0;this.sampleRate=8000;this.destination={};this.osc=[];}resume(){this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}createGain(){return new Node();}createDynamicsCompressor(){return new Node();}createConvolver(){return new Node();}createBiquadFilter(){return new Node();}createStereoPanner(){return new Node();}createBuffer(c,length){return {getChannelData:()=>new Float32Array(length)};}createOscillator(){const n=new Node();this.osc.push(n);return n;}}
const setup=()=>{const storage={value:null,getItem(){return this.value;},setItem(k,v){this.value=v;}},jobs=new Map();let next=0;const audio=new SpaceAudio({storage,Context,timer:fn=>{const id=next++;jobs.set(id,fn);return id;},clear:id=>jobs.delete(id)});return {audio,storage,jobs};};
test('music waits for a gesture, uses one scheduler and respects separate persisted volume controls',async()=>{
 const {audio,jobs,storage}=setup();assert.equal(audio.ctx,null);assert.equal(jobs.size,0);assert.equal(await audio.unlock(),true);assert.equal(jobs.size,1);const oscillators=audio.ctx.osc.length;await audio.unlock();assert.equal(jobs.size,1);assert.equal(audio.ctx.osc.length,oscillators);audio.update('musicVolume',.2);audio.update('effectsVolume',.7);assert.equal(JSON.parse(storage.value).effectsVolume,.7);audio.update('music',false);assert.equal(jobs.size,0);assert.equal(audio.nodes.size,0);audio.play('research');assert.ok(audio.ctx.osc.length>oscillators);audio.update('effects',false);const count=audio.ctx.osc.length;audio.play('research');assert.equal(audio.ctx.osc.length,count);
});
test('backgrounding stops all scheduled music and returning remains silent until another gesture',async()=>{
 const {audio,jobs}=setup();await audio.unlock();audio.setHidden(true);assert.equal(audio.ctx.state,'suspended');assert.equal(jobs.size,0);const count=audio.ctx.osc.length;audio.play('ship');audio.setHidden(false);assert.equal(audio.ctx.osc.length,count);assert.equal(jobs.size,0);await audio.unlock();assert.equal(jobs.size,1);
});
test('completion cues are finite and burst notifications select a single high-priority sound',async()=>{
 const {audio}=setup();await audio.unlock();audio.update('music',false);for(const cue of SOUND_CUES){audio.ctx.currentTime+=2;audio.play(cue);}assert.ok(audio.ctx.osc.every(o=>o.started.every(Number.isFinite)));audio.ctx.currentTime+=2;const before=audio.ctx.osc.length;audio.notify([{sound:'build'},{sound:'research'},{type:'war'}]);assert.equal(audio.ctx.osc.length-before,2);audio.notify([{sound:'build'}]);assert.equal(audio.ctx.osc.length-before,2);
});
test('unsupported audio and malformed preferences cannot break game controls',async()=>{
 assert.deepEqual(audioPreferences({music:'yes',musicVolume:99,effectsVolume:-3}),{...AUDIO_DEFAULTS,musicVolume:1,effectsVolume:0});const a=new SpaceAudio({Context:null,storage:{getItem(){throw Error('Unavailable');}}});assert.equal(await a.unlock(),false);assert.doesNotThrow(()=>a.play('research'));assert.doesNotThrow(()=>a.update('music',false));
});
