import { readdir, readFile, mkdir, rm, writeFile } from 'node:fs/promises';
import { resolve, relative, dirname } from 'node:path';
import { createHash } from 'node:crypto';
const root = resolve(import.meta.dirname, '..');
const output = resolve(root, 'docs');
const check = process.argv.includes('--check');
async function files(folder) {
  const result = [];
  for (const e of await readdir(folder, { withFileTypes: true })) {
    const p = resolve(folder, e.name);
    if (e.isDirectory()) result.push(...await files(p)); else result.push(p);
  }
  return result.sort();
}
const contents = new Map();
for (const path of await files(resolve(root, 'src'))) contents.set('build/' + relative(resolve(root, 'src'), path), await readFile(path, 'utf8'));
for (const path of await files(resolve(root, 'web'))) contents.set(relative(resolve(root, 'web'), path), await readFile(path, 'utf8'));
contents.set('.nojekyll', '');
const hash = createHash('sha256').update([...contents].map(([p, c]) => p + '\n' + c).join('\n')).digest('hex').slice(0, 16);
const assets = ['./', ...[...contents.keys()].filter(p => p !== '.nojekyll').map(p => './' + p)];
contents.set('sw.js', `// Generated by scripts/build.mjs. Do not edit.\nconst CACHE = 'orbit3077-${hash}';\nconst ASSETS = ${JSON.stringify(assets)};\nself.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS.map(url => new Request(url, {cache:'reload'}))))));\nself.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('orbit3077-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())));\nself.addEventListener('fetch', event => {\n  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;\n  event.respondWith(caches.open(CACHE).then(async cache => {\n    if (event.request.mode === 'navigate') return (await cache.match('./index.html')) || fetch(event.request);\n    return (await cache.match(event.request)) || fetch(event.request);\n  }));\n});\n`);
if (check) {
  let valid = true;
  for (const [path, content] of contents) {
    try { if (await readFile(resolve(output, path), 'utf8') !== content) { console.error('Out of date:', path); valid = false; } }
    catch { console.error('Missing:', path); valid = false; }
  }
  try { for (const p of await files(output)) if (!contents.has(relative(output, p))) { console.error('Unexpected output:', relative(output, p)); valid = false; } } catch { valid = false; }
  if (!valid) process.exitCode = 1; else console.log(`Build verified (${contents.size} files, ${hash}).`);
} else {
  await rm(output, { recursive: true, force: true });
  for (const [path, content] of contents) { await mkdir(dirname(resolve(output, path)), { recursive: true }); await writeFile(resolve(output, path), content); }
  console.log(`Built ${contents.size} files (${hash}).`);
}
