import { FACTIONS } from './data.js';
import { esc,fmt,opts,button } from './ui-format.js';
import { dateLabel } from './state.js';
import { inboxSignal, communicationReady, OFFER_TERMS, offerIssue } from './communications.js';
const statuses={open:'Offen',accepted:'Angenommen',rejected:'Abgelehnt',expired:'Unbeantwortet',withdrawn:'Zurückgezogen',information:'Erklärung'};
export function communicationPanel(state,ui,p) {
  const b=p.buildings.find(b=>b.id===ui.communicationBuilding&&b.type==='commCenter'&&!b.remaining);
  if(p.owner!=='player'||!b)return '<p class="empty">Diese Kommunikationszentrale ist nicht mehr verfügbar. Die Korrespondenz bleibt im Reichsarchiv erhalten.</p>';
  const signal=inboxSignal(state),ready=communicationReady(state);
  const mode=ui.inboxMode??'open',messages=state.communications.messages.filter(m=>mode==='open'?m.status==='open':m.status!=='open');
  const faction=Object.hasOwn(state.relations,ui.offerFaction)?ui.offerFaction:'ilyri',type=ui.offerType==='pact'?'pact':'trade';
  const issue=offerIssue(state,faction,type);
  return `<div class="inbox-overview"><strong class="inbox-count ${signal.urgent?'urgent':''}">${signal.count}</strong><span>offene Anfragen & Angebote<br><small>Gemeinsamer Posteingang aller Planeten</small></span></div>${b.status!=='aktiv'?'<p class="research-condition unmet">Diese Zentrale ist nicht versorgt. Der Posteingang bleibt erhalten; zum Antworten wird eine aktive Zentrale benötigt.</p>':''}<div class="subnav"><button data-action="subtab" data-field="inboxMode" data-value="open" class="${mode==='open'?'active':''}">Offen</button><button data-action="subtab" data-field="inboxMode" data-value="archive" class="${mode==='archive'?'active':''}">Archiv${signal.unread?' · Neu':''}</button></div>${messages.map(m=>{
    const incoming=m.to==='player',other=incoming?m.from:m.to,days=m.expires-state.day;
    return `<div class="detail-card message-card"><div class="message-meta"><span>${incoming?'Von':'An'} ${esc(FACTIONS[other].name)}</span><time>${dateLabel(m.created)}</time></div><div class="card-heading"><strong>${esc(m.title)}</strong><span class="status-badge ${m.status==='open'&&days<=7?'deadline':''}">${m.status==='open'?`${days} Tage Frist`:statuses[m.status]}</span></div><p>${esc(m.body)}</p>${OFFER_TERMS[m.type]?`<p class="note">Bei Annahme: ${fmt(OFFER_TERMS[m.type].cost)} ¢ Verwaltungskosten je Reich${m.type==='pact'?' · 180 Tage Laufzeit':''}.</p>`:''}${m.reason?`<p class="note">${esc(m.reason)}</p>`:''}${m.status==='open'?(incoming?`<div class="button-row">${button('Annehmen','message-answer',`data-id="${m.id}" data-choice="accept"`,!ready||state.credits<OFFER_TERMS[m.type].cost)}${button('Ablehnen','message-answer',`data-id="${m.id}" data-choice="reject"`,!ready)}</div>`:button('Angebot zurückziehen','message-withdraw',`data-id="${m.id}"`)):''}</div>`;
  }).join('')||'<p class="empty">Hier liegen derzeit keine Nachrichten.</p>'}<div class="section-title">Angebot senden</div><label class="form-label">Empfänger</label><select class="select" data-field="offerFaction">${opts(Object.keys(state.relations).map(id=>[id,FACTIONS[id].name]),faction)}</select><label class="form-label">Abkommen</label><select class="select" data-field="offerType">${opts([['trade','Handelsabkommen'],['pact','Nichtangriffspakt']],type)}</select><p class="note">${OFFER_TERMS[type].cost} ¢ bei Einigung. Die andere Regierung antwortet nach drei Spieltagen; offene Angebote gelten höchstens 30 Tage.</p>${issue?`<p class="research-condition unmet">${esc(issue)}</p>`:''}${button('Angebot übermitteln','message-send',`data-faction="${faction}" data-type="${type}"`,!ready||Boolean(issue)||state.credits<OFFER_TERMS[type].cost)}<div class="divider"></div>${button('Zentrale verwalten','communication-manage',`data-id="${b.id}"`)}`;
}
