import { FACTIONS, IDEOLOGIES } from './data.js';
const btn=(label,id,kind,disabled=false)=>`<button class="button secondary" data-action="diplomacy" data-faction="${id}" data-kind="${kind}" ${disabled?'disabled':''}>${label}</button>`;
export function diplomacyPanel(state,ui) {
 return `<p class="lede">Beziehungen eröffnen Abkommen. Handel erlaubt den Warenverkauf; Partnerschaften stärken Forschung und Versorgung. Sanktionen bremsen die gegnerische Produktion und kosten laufend Credits.</p>${Object.entries(state.relations).map(([id,r])=>{
 const exists=state.planets.some(p=>p.owner===id),pact=r.pactUntil>state.day;
 return `<div class="detail-card"><div class="card-heading"><strong style="color:${FACTIONS[id].color}">${FACTIONS[id].name}</strong><span class="status-badge">${!exists?'Keine Kolonien':r.war?'Krieg':r.embargo?'Sanktionen':r.cooperation?'Partner':r.trade?'Handel':'Frieden'}</span></div><p>${FACTIONS[id].species} · ${IDEOLOGIES[FACTIONS[id].ideology].name}<br>Beziehungen: ${Math.round(r.score)} / 100</p><p class="note">Handel ab 0 · Nichtangriffspakt ab 35 · Partnerschaft ab 50</p>${r.trade?'<p>Handel offen: Frachter können Waren verkaufen.</p>':''}${r.cooperation?'<p>Partnerschaft: +8 % Forschung · +12 % Exporterlös.<br>Im Krieg alle 60 Tage: +12 Legierungen, +4 Waffen, +4 Verteidigung, sofern der Partner Vorräte hat.</p>':''}${pact?`<p>Nichtangriffspakt: noch ${r.pactUntil-state.day} Tage. Vor einer Kriegserklärung kündigen.</p>`:''}${r.embargo?'<p>Sanktionen: Produktion dieses Reichs −15 %; dein Haushalt −1,5 ¢ / Tag. Handel und Partnerschaft sind gesperrt.</p>':''}
 ${r.war?btn('Waffenstillstand · 120 ¢',id,'peace',state.credits<120):`${btn(r.envoyReady>state.day?`Gesandtschaft in ${r.envoyReady-state.day} Tagen`:'Gesandtschaft · 60 ¢',id,'envoy',state.credits<60||r.envoyReady>state.day)}${!r.trade?btn('Handelsabkommen · 50 ¢',id,'trade',!exists||r.embargo||r.score<0||state.credits<50):`<button class="button primary" data-action="trade-open" data-faction="${id}">Handelsroute einrichten</button>`}${btn(pact?'Pakt kündigen · −15 Beziehungen':'Nichtangriffspakt · 100 ¢',id,pact?'cancel-pact':'pact',!pact&&(!exists||r.embargo||r.score<35||state.credits<100))}${btn(r.cooperation?'Partnerschaft beenden':'Partnerschaft · 180 ¢',id,r.cooperation?'cancel-cooperation':'cooperation',!r.cooperation&&(!exists||!r.trade||r.embargo||r.score<50||state.credits<180))}`}
 ${btn(r.embargo?'Sanktionen aufheben':'Sanktionen · 1,5 ¢ / Tag',id,r.embargo?'lift-embargo':'embargo',!exists&&!r.embargo)}${!r.war?`<button class="button danger" data-action="war-confirm" data-faction="${id}" ${pact||!exists?'disabled':''}>${ui.warConfirm===id?'Kriegserklärung bestätigen':'Krieg erklären'}</button>`:''}</div>`;
 }).join('')}`;
}
