import { RESEARCH_BRANCHES, TECHNOLOGIES } from './technology-data.js';
import { researchBlock, technologyEffects, technologyText } from './technology.js';
import { researchDays } from './research.js';
const pct = n => Math.round((n - 1) * 100);
export function researchPanel(state, ui) {
  const branch = Object.hasOwn(RESEARCH_BRANCHES, ui.researchBranch) ? ui.researchBranch : 'energy';
  const progress = state.tech.length;
  const active = state.research;
  const effects = technologyEffects(state);
  return `<p class="lede">60 Technologien, zehn Fachgebiete. Kleine Boni bauen aufeinander auf. Sieben Spezialisierungen und drei militärische Zweige führen bis zu planetaren und stellaren Megabauten.</p><div class="research-overview"><span>${progress} / 60 erforscht</span><span>Laborertrag +${pct(effects.science)} %</span></div>${active ? `<div class="detail-card research-active"><div class="eyebrow">AKTUELLES PROJEKT</div><strong>${TECHNOLOGIES[active.id].name}</strong><p>Noch ${active.remaining} von ${active.total} Tagen</p><div class="progress"><span style="width:${(1 - active.remaining / active.total) * 100}%"></span></div></div>` : '<p class="note">Kein laufendes Forschungsprojekt.</p>'}<div class="research-branches">${Object.entries(RESEARCH_BRANCHES).map(([id, b]) => `<button data-action="research-branch" data-id="${id}" class="${id === branch ? 'active' : ''}" style="--branch-color:${b.color}">${b.name}<small>${state.tech.filter(t => TECHNOLOGIES[t].branch === id).length} / 6</small></button>`).join('')}</div><div class="section-title">${RESEARCH_BRANCHES[branch].name}<span>${RESEARCH_BRANCHES[branch].description}</span></div><div class="research-tree">${Object.entries(TECHNOLOGIES).filter(([, t]) => t.branch === branch).map(([id, t]) => {
    const done = state.tech.includes(id), running = active?.id === id;
    const blocked = researchBlock(state, id);
    const excluded = (t.excludes ?? []).some(other => state.tech.includes(other));
    const prerequisites = [...t.requires, ...(t.requiresAny ?? [])];
    return `<article data-tech-id="${id}" class="detail-card tech-card ${done ? 'researched' : excluded ? 'excluded' : blocked ? 'locked' : 'available'}" style="--branch-color:${RESEARCH_BRANCHES[branch].color}"><div class="card-heading"><span class="tech-tier">${t.tier}</span><strong>${t.name}</strong><span class="status-badge">${done ? 'Erforscht' : running ? `${active.remaining} Tage` : excluded ? 'Andere Wahl' : blocked ? 'Gesperrt' : 'Bereit'}</span></div>${t.focus ? `<div class="tech-focus">Spezialisierung: ${t.focus}</div>` : ''}<p>${t.description ?? technologyText(t.effects)}</p>${t.description && Object.keys(t.effects).length ? `<p class="note">${technologyText(t.effects)}</p>` : ""}${prerequisites.length ? `<div class="tech-requires">Voraussetzungen${t.requiresAny ? ' · eine Spezialisierung erforderlich' : ''}<div>${prerequisites.map(required => `<button class="tech-link ${state.tech.includes(required) ? 'done' : ''}" data-action="research-focus" data-id="${required}">${state.tech.includes(required) ? '✓ ' : ''}${TECHNOLOGIES[required].name}</button>`).join('')}</div></div>` : '<p class="note">Grundlagentechnologie · keine Voraussetzung</p>'}${t.excludes ? `<p class="note">Alternative: ${TECHNOLOGIES[t.excludes[0]].name}. Du kannst nur eine dieser Richtungen erforschen.</p>` : ''}${blocked && !done ? `<p class="note">${blocked}</p>` : ''}${!done && !running ? `<button class="button secondary" data-action="research-start" data-tech="${id}" ${blocked || active || state.science < t.cost ? 'disabled' : ''}>${t.cost} Punkte · ${researchDays(state, id)} Tage · Erforschen</button>` : ''}</article>`;
  }).join('')}</div><p class="note">Technologien wirken dauerhaft. Politische Boni verändern Laborertrag und Entwicklungsdauer zusätzlich. Bereits laufende Aufträge behalten ihre Restzeit.</p>`;
}
