import { BUILDINGS, TECHNOLOGIES, RESOURCES } from './data.js';
import { MILITARY_BUILDINGS, STRATEGIC_WEAPONS, CAMPAIGN_GOALS } from './military-data.js';
import { baseStats, strikeError, goalValue } from './strategic.js';
import { getPlanet } from './state.js';
import { technologyEffects } from './technology.js';
const n = v => Math.floor(v).toLocaleString('de-DE');
const esc = v => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function militaryPanel(state, ui) {
  const own = state.planets.filter(p => p.owner === 'player');
  const p = getPlanet(state, ui.planetId)?.owner === 'player' ? getPlanet(state, ui.planetId) : own[0];
  if (ui.fleetMode === 'goals') return `<p class="lede">Baue ein interstellares Reich auf. Jeder Meilenstein zahlt seine Belohnung einmal aus; du kannst danach weiterspielen.</p>${CAMPAIGN_GOALS.map(g => `<div class="detail-card"><div class="card-heading"><strong>${g.name}</strong><span class="status-badge">${state.milestones.includes(g.id) ? '✓ Erreicht' : `${n(goalValue(state,g.kind))} / ${n(g.target)}`}</span></div><p>${({colonies:"Kolonien",research:"Abgeschlossene Forschungen",bases:"Fertiggestellte Basen",shields:"Geladene Schildpunkte",mega:"Fertiggestellte Resonanzschmieden"})[g.kind]}<br>Belohnung: ${n(g.credits)} ¢ · ${n(g.science)} Forschung</p><div class="progress"><span style="width:${Math.min(100,goalValue(state,g.kind)/g.target*100)}%"></span></div></div>`).join('')}`;
  const select = `<label class="form-label">Startplanet / Basis</label><select class="select" data-field="ownPlanet">${own.map(q => `<option value="${q.id}" ${q.id === p.id ? 'selected' : ''}>${esc(q.name)}</option>`).join('')}</select>`;
  if (ui.fleetMode === 'bases') {
    const b = baseStats(state,p);
    return `${select}<div class="detail-card"><div class="stat-line"><span>Geladene Schilde</span><strong>${n(p.shield)} / ${n(b.capacity)}</strong></div><div class="stat-line"><span>Aufladung / Tag</span><strong>+${n(b.regen)}</strong></div><div class="stat-line"><span>Orbit / Befestigung</span><strong>${n(b.orbital)} / ${n(b.fortification)}</strong></div><div class="stat-line"><span>Abfangwirkung</span><strong>${n(b.interception*100)} %</strong></div><div class="stat-line"><span>Stellarer Schutz</span><strong>${n(b.starBarrier)}</strong></div></div><p class="note">Nur fertiggestellte, versorgte Anlagen wirken. Schilde laden langsam auf; bei Ausfall verlieren sie ihre Kapazität. Mehrere Anlagen verstärken das Netz, Abfangwirkung bis 75 %.</p>${Object.entries(MILITARY_BUILDINGS).map(([id,d]) => `<div class="detail-card"><strong style="color:${d.color}">${d.glyph} ${d.name}</strong><p>${d.description}</p><p class="note">${d.days} Bautage · ${d.workers} Personal · ${d.upkeep} ¢ / Tag<br>${state.tech.includes(d.requiredTech) ? 'Technologie freigeschaltet' : `Benötigt: ${TECHNOLOGIES[d.requiredTech].name}`}</p><button class="button secondary" data-action="build-detail" data-type="${id}">Bauplanung öffnen</button></div>`).join('')}`;
  }
  const targets = state.planets.filter(q => q.owner && q.owner !== 'player' && !q.destroyed);
  const target = targets.find(q => q.id === ui.strikeTarget) ?? targets[0];
  return `${state.strikes.filter(s=>s.owner!=='player'&&getPlanet(state,s.target)?.owner==='player').map(s=>`<div class="alert"><strong>FEINDLICHER FERNANGRIFF</strong><br>${STRATEGIC_WEAPONS[s.type].name} → ${esc(getPlanet(state,s.target).name)}<br>${s.phase==='charge'?`Noch ${s.remaining} Ladetage + ${s.flight} Flugtage`:`Einschlag in ${s.remaining} Tagen`}</div>`).join('')}${select}<label class="form-label">Zielplanet</label><select class="select" data-field="strikeTarget">${targets.map(q => `<option value="${q.id}" ${q.id === target?.id ? 'selected' : ''}>${esc(q.name)} · ${esc(q.system)}</option>`).join('')}</select><p class="note">Ladungen werden sofort bezahlt. Versorgungsausfälle pausieren das Laden. Eine verlorene Startanlage vernichtet ihre Ladung; gestartete Waffen fliegen weiter. Waffenstillstände brechen den Einschlag ab.</p>${Object.entries(STRATEGIC_WEAPONS).map(([id,w]) => {
    const error = strikeError(state,p,target,id), key = `${id}:${p.id}:${target?.id}`, confirm = ui.strikeConfirm === key;
    return `<div class="detail-card"><strong>${w.name}</strong><p>${w.description}</p><p class="note">Stärke ${n(w.power*technologyEffects(state).strikePower)} · ${w.charge} Ladetage · ${p.system === target?.system ? 4 : '10–16'} Flugtage<br>Startanlage: ${BUILDINGS[w.facility].name}</p><div class="cost-line">${Object.entries(w.cost).map(([k,v]) => `${n(v)} ${k==='credits'?'¢':RESOURCES[k].short}`).join(' · ')}</div>${error ? `<p class="note">${error}</p>` : ''}${w.starKiller && target ? `<div class="alert">Zerstört den Stern und alle ${state.planets.filter(q=>q.system===target.system&&!q.destroyed).length} Welten des Systems endgültig, falls der stellare Schutz durchbrochen wird.</div>` : w.planetKiller ? '<div class="alert">Ein durchdringender Treffer zerstört den Planeten endgültig. Er kann danach nicht besiedelt werden.</div>' : ''}<button class="button ${w.planetKiller||w.starKiller?'danger':'primary'}" data-action="strike-launch" data-type="${id}" data-source="${p.id}" data-target="${target?.id ?? ''}" ${error?'disabled':''}>${confirm?'Zerstörung bestätigen':w.planetKiller||w.starKiller?'Einsatz vorbereiten':'Ladung beginnen'}</button></div>`;
  }).join('')}<div class="section-title">Waffenladungen und Anflüge</div>${state.strikes.map(s=>`<div class="detail-card"><strong>${STRATEGIC_WEAPONS[s.type].name}${s.owner!=='player'?' · FEINDLICH':''}</strong><p>${esc(getPlanet(state,s.source).name)} → ${esc(getPlanet(state,s.target).name)}<br>${s.phase==='charge'?'Lädt (bei Versorgung)':'Einschlag in'}: ${s.remaining} Tage</p><div class="progress"><span style="width:${(1-s.remaining/s.total)*100}%"></span></div>${s.owner==='player'&&s.phase==='charge'?`<button class="button secondary" data-action="strike-cancel" data-id="${s.id}">Abbrechen · keine Erstattung</button>`:''}</div>`).join('')||'<p class="note">Keine aktiven Fernangriffe.</p>'}`;
}
